<h1 style = "color: blue">Loan Prediction Using KNN, Decision Tree, SVM, Logistic Regression, Naive Bayes, Random Forest</h1>

 Reading the Dataset 

In [2]:
import numpy as np
import pandas as pd

 Importing the train dataset

In [3]:
df = pd.read_csv('train.csv')
df.head(10)

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   
5  LP001011   Male     Yes          2      Graduate           Yes   
6  LP001013   Male     Yes          0  Not Graduate            No   
7  LP001014   Male     Yes         3+      Graduate            No   
8  LP001018   Male     Yes          2      Graduate            No   
9  LP001020   Male     Yes          1      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   
5             5417             4196.0       267.0             360.0   
6             2333             1516.0        95.0             360.0   
7             3036             2504.0       158.0             360.0   
8             4006             1526.0       168.0             360.0   
9            12841            10968.0       349.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y  
5             1.0         Urban           Y  
6             1.0         Urban           Y  
7             0.0     Semiurban           N  
8             1.0         Urban           Y  
9             1.0     Semiurban           N

 Importing the test dataset

In [4]:
test = pd.read_csv('test.csv')
test.head(10)

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0  LP001015    Male     Yes          0      Graduate            No   
1  LP001022    Male     Yes          1      Graduate            No   
2  LP001031    Male     Yes          2      Graduate            No   
3  LP001035    Male     Yes          2      Graduate            No   
4  LP001051    Male      No          0  Not Graduate            No   
5  LP001054    Male     Yes          0  Not Graduate           Yes   
6  LP001055  Female      No          1  Not Graduate            No   
7  LP001056    Male     Yes          2  Not Graduate            No   
8  LP001059    Male     Yes          2      Graduate           NaN   
9  LP001067    Male      No          0  Not Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                  0       110.0             360.0   
1             3076               1500       126.0             360.0   
2             5000               1800       208.0             360.0   
3             2340               2546       100.0             360.0   
4             3276                  0        78.0             360.0   
5             2165               3422       152.0             360.0   
6             2226                  0        59.0             360.0   
7             3881                  0       147.0             360.0   
8            13633                  0       280.0             240.0   
9             2400               2400       123.0             360.0   

   Credit_History Property_Area  
0             1.0         Urban  
1             1.0         Urban  
2             1.0         Urban  
3             NaN         Urban  
4             1.0         Urban  
5             1.0         Urban  
6             1.0     Semiurban  
7             0.0         Rural  
8             1.0         Urban  
9             1.0     Semiurban

 Gathering information of train dataset

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


 Computing the mode of each categorical variable

In [6]:
print('Gender Mode: ', df['Gender'].mode())
print('Married  Mode: ', df['Married'].mode())
print('Self_Employed Mode: ', df['Self_Employed'].mode())
print('Credit_History Mode: ', df['Credit_History'].mode())


Gender Mode:  0    Male
Name: Gender, dtype: object
Married  Mode:  0    Yes
Name: Married, dtype: object
Self_Employed Mode:  0    No
Name: Self_Employed, dtype: object
Credit_History Mode:  0    1.0
Name: Credit_History, dtype: float64


 Boolean Indexing

In [7]:
df[['Loan_Amount_Term', 'LoanAmount']][df['Loan_Amount_Term'].isnull()]

Loan_Amount_Term  LoanAmount
19                NaN       115.0
36                NaN       100.0
44                NaN        96.0
45                NaN        88.0
73                NaN        95.0
112               NaN       152.0
165               NaN       182.0
197               NaN       120.0
223               NaN       175.0
232               NaN       120.0
335               NaN        70.0
367               NaN       124.0
421               NaN        80.0
423               NaN       110.0

Quick overview of the distribution of values

In [8]:
df['Dependents'].value_counts()

Dependents
0     345
1     102
2     101
3+     51
Name: count, dtype: int64

 Value Substitution

In [9]:
df['Dependents'].replace('3+',3,inplace = True)
df['Dependents'].value_counts()

Dependents
0    345
1    102
2    101
3     51
Name: count, dtype: int64

 Boolean Indexing

In [10]:
df[['Dependents', 'Married']][df['Dependents'].isnull()]

Dependents Married
102        NaN     Yes
104        NaN     NaN
120        NaN     Yes
226        NaN     Yes
228        NaN     NaN
293        NaN      No
301        NaN     Yes
332        NaN      No
335        NaN     Yes
346        NaN     Yes
355        NaN      No
435        NaN     NaN
517        NaN     Yes
571        NaN     Yes
597        NaN      No

 Missing value imputation

In [11]:
df['Gender'].fillna('Male', inplace = True)
df['Married'].fillna('Yes', inplace = True)
df['Self_Employed'].fillna('No', inplace = True)
df['Credit_History'].fillna('1.0', inplace = True)
df['LoanAmount'].fillna((df['LoanAmount'].mean()), inplace = True)
df['Loan_Amount_Term'].fillna('84', inplace = True)
df['Dependents'].fillna(0, inplace = True)

C:\Users\KIIT\AppData\Local\Temp\ipykernel_26128\1924314904.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '1.0' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['Credit_History'].fillna('1.0', inplace = True)
C:\Users\KIIT\AppData\Local\Temp\ipykernel_26128\1924314904.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '84' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['Loan_Amount_Term'].fillna('84', inplace = True)


 DataType conversion 

In [12]:
df['Dependents'] = df['Dependents'].astype('int')
df['Dependents'].dtype

dtype('int32')

 Missing Value Detection

In [13]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

Column Removal or Column Dropping

In [14]:
df.drop('Loan_ID', axis = 1, inplace = True)

Computing the number of distinct values in each column

In [15]:
df.nunique()

Gender                 2
Married                2
Dependents             4
Education              2
Self_Employed          2
ApplicantIncome      505
CoapplicantIncome    287
LoanAmount           204
Loan_Amount_Term      11
Credit_History         3
Property_Area          3
Loan_Status            2
dtype: int64

 Summary Statistics Computation 

In [16]:
df.describe()

Dependents  ApplicantIncome  CoapplicantIncome  LoanAmount
count  614.000000       614.000000         614.000000  614.000000
mean     0.744300      5403.459283        1621.245798  146.412162
std      1.009623      6109.041673        2926.248369   84.037468
min      0.000000       150.000000           0.000000    9.000000
25%      0.000000      2877.500000           0.000000  100.250000
50%      0.000000      3812.500000        1188.500000  129.000000
75%      1.000000      5795.000000        2297.250000  164.750000
max      3.000000     81000.000000       41667.000000  700.000000

 Identifying which columns in the DataFrame contain non-numeric data

In [17]:
obj_col = df.select_dtypes('object').columns
obj_col

Index(['Gender', 'Married', 'Education', 'Self_Employed', 'Loan_Amount_Term',
       'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

Converting Object to Numeric data type

In [18]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()
df[obj_col] = df[obj_col].astype(str)
df[obj_col] = oe.fit_transform(df[obj_col])
df.head(3)

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0     1.0      0.0           0        0.0            0.0             5849   
1     1.0      1.0           1        0.0            0.0             4583   
2     1.0      1.0           0        0.0            1.0             3000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0  146.412162               6.0             1.0   
1             1508.0  128.000000               6.0             1.0   
2                0.0   66.000000               6.0             1.0   

   Property_Area  Loan_Status  
0            2.0          1.0  
1            0.0          0.0  
2            2.0          1.0

Changing Variable 

In [19]:
data = df

 Summary Statistics Computation 

In [20]:
df.describe()

Gender     Married  Dependents   Education  Self_Employed  \
count  614.000000  614.000000  614.000000  614.000000     614.000000   
mean     0.817590    0.653094    0.744300    0.218241       0.133550   
std      0.386497    0.476373    1.009623    0.413389       0.340446   
min      0.000000    0.000000    0.000000    0.000000       0.000000   
25%      1.000000    0.000000    0.000000    0.000000       0.000000   
50%      1.000000    1.000000    0.000000    0.000000       0.000000   
75%      1.000000    1.000000    1.000000    0.000000       0.000000   
max      1.000000    1.000000    3.000000    1.000000       1.000000   

       ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  614.000000        614.000000   
mean       5403.459283        1621.245798  146.412162          5.739414   
std        6109.041673        2926.248369   84.037468          1.325067   
min         150.000000           0.000000    9.000000          0.000000   
25%        2877.500000           0.000000  100.250000          6.000000   
50%        3812.500000        1188.500000  129.000000          6.000000   
75%        5795.000000        2297.250000  164.750000          6.000000   
max       81000.000000       41667.000000  700.000000         10.000000   

       Credit_History  Property_Area  Loan_Status  
count      614.000000     614.000000   614.000000  
mean         0.855049       1.037459     0.687296  
std          0.352339       0.787482     0.463973  
min          0.000000       0.000000     0.000000  
25%          1.000000       0.000000     0.000000  
50%          1.000000       1.000000     1.000000  
75%          1.000000       2.000000     1.000000  
max          1.000000       2.000000     1.000000

 Standardization

In [21]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
df.iloc[:,:-1] = ss.fit_transform(df.iloc[:,:-1])
df.head()


Gender   Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0  0.472343 -1.372089   -0.737806  -0.528362      -0.392601         0.072991   
1  0.472343  0.728816    0.253470  -0.528362      -0.392601        -0.134412   
2  0.472343  0.728816   -0.737806  -0.528362       2.547117        -0.393747   
3  0.472343  0.728816   -0.737806   1.892641      -0.392601        -0.462062   
4  0.472343 -1.372089   -0.737806  -0.528362      -0.392601         0.097728   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0          -0.554487    0.000000          0.196819        0.411733   
1          -0.038732   -0.219273          0.196819        0.411733   
2          -0.554487   -0.957641          0.196819        0.411733   
3           0.251980   -0.314547          0.196819        0.411733   
4          -0.554487   -0.064454          0.196819        0.411733   

   Property_Area  Loan_Status  
0       1.223298          1.0  
1      -1.318513          0.0  
2       1.223298          1.0  
3       1.223298          1.0  
4       1.223298          1.0

 Splitting the Data

In [22]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]
x.head()

Gender   Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0  0.472343 -1.372089   -0.737806  -0.528362      -0.392601         0.072991   
1  0.472343  0.728816    0.253470  -0.528362      -0.392601        -0.134412   
2  0.472343  0.728816   -0.737806  -0.528362       2.547117        -0.393747   
3  0.472343  0.728816   -0.737806   1.892641      -0.392601        -0.462062   
4  0.472343 -1.372089   -0.737806  -0.528362      -0.392601         0.097728   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0          -0.554487    0.000000          0.196819        0.411733   
1          -0.038732   -0.219273          0.196819        0.411733   
2          -0.554487   -0.957641          0.196819        0.411733   
3           0.251980   -0.314547          0.196819        0.411733   
4          -0.554487   -0.064454          0.196819        0.411733   

   Property_Area  
0       1.223298  
1      -1.318513  
2       1.223298  
3       1.223298  
4       1.223298

 Train-Test split on the dataset

In [23]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y,random_state = 4, test_size = 0.25, stratify = y)

 Making Machine Learning Model that fits and evaluates on training and testing data

In [24]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
def mymodel(model):
    model.fit(xtrain,ytrain)
    ypred = model.predict(xtest)
    train_accuracy = model.score(xtrain,ytrain)
    test_accuracy = model.score(xtest, ytest)
    print(str(model)[:-2], 'Accuracy')
    print('Accuracy: ', accuracy_score(ytest,ypred), "\nClassification Report: \n", classification_report(ytest, ypred), '\nConfusion Matrix: \n', confusion_matrix(ytest, ypred))
    print(f'Training Accuracy: {train_accuracy}\nTesting Accuracy: {test_accuracy}')
    print()
    print()
    return model
    

 Importing Libraries foe Accuracy score, Confusion Matrix and Classification Report

In [25]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

Using KNN (K-Nearest Neighbors)

In [26]:
from sklearn.neighbors import KNeighborsClassifier
knn = mymodel(KNeighborsClassifier())

KNeighborsClassifier Accuracy
Accuracy:  0.8246753246753247 
Classification Report: 
               precision    recall  f1-score   support

         0.0       0.86      0.52      0.65        48
         1.0       0.82      0.96      0.88       106

    accuracy                           0.82       154
   macro avg       0.84      0.74      0.77       154
weighted avg       0.83      0.82      0.81       154
 
Confusion Matrix: 
 [[ 25  23]
 [  4 102]]
Training Accuracy: 0.8217391304347826
Testing Accuracy: 0.8246753246753247




 Using SVM Model

In [27]:
from sklearn.svm import SVC
svc = mymodel(SVC())

SVC Accuracy
Accuracy:  0.8246753246753247 
Classification Report: 
               precision    recall  f1-score   support

         0.0       1.00      0.44      0.61        48
         1.0       0.80      1.00      0.89       106

    accuracy                           0.82       154
   macro avg       0.90      0.72      0.75       154
weighted avg       0.86      0.82      0.80       154
 
Confusion Matrix: 
 [[ 21  27]
 [  0 106]]
Training Accuracy: 0.8108695652173913
Testing Accuracy: 0.8246753246753247




 Using Decision Tree Model

In [28]:
from sklearn.tree import DecisionTreeClassifier
dt= mymodel(DecisionTreeClassifier())

DecisionTreeClassifier Accuracy
Accuracy:  0.7467532467532467 
Classification Report: 
               precision    recall  f1-score   support

         0.0       0.61      0.52      0.56        48
         1.0       0.80      0.85      0.82       106

    accuracy                           0.75       154
   macro avg       0.70      0.68      0.69       154
weighted avg       0.74      0.75      0.74       154
 
Confusion Matrix: 
 [[25 23]
 [16 90]]
Training Accuracy: 1.0
Testing Accuracy: 0.7467532467532467




 Using Logistic Regression Model

In [29]:
from sklearn.linear_model import LogisticRegression
lr = mymodel(LogisticRegression())

LogisticRegression Accuracy
Accuracy:  0.8376623376623377 
Classification Report: 
               precision    recall  f1-score   support

         0.0       1.00      0.48      0.65        48
         1.0       0.81      1.00      0.89       106

    accuracy                           0.84       154
   macro avg       0.90      0.74      0.77       154
weighted avg       0.87      0.84      0.82       154
 
Confusion Matrix: 
 [[ 23  25]
 [  0 106]]
Training Accuracy: 0.8043478260869565
Testing Accuracy: 0.8376623376623377




 Using Gaussian Naive Bayes Model

In [30]:
from sklearn.naive_bayes import GaussianNB
gnb = mymodel(GaussianNB())

GaussianNB Accuracy
Accuracy:  0.8311688311688312 
Classification Report: 
               precision    recall  f1-score   support

         0.0       0.96      0.48      0.64        48
         1.0       0.81      0.99      0.89       106

    accuracy                           0.83       154
   macro avg       0.88      0.73      0.76       154
weighted avg       0.85      0.83      0.81       154
 
Confusion Matrix: 
 [[ 23  25]
 [  1 105]]
Training Accuracy: 0.8021739130434783
Testing Accuracy: 0.8311688311688312




 Using Random Forest Model

In [31]:
from sklearn.ensemble import RandomForestClassifier
rfc = mymodel(RandomForestClassifier(n_estimators = 80, max_depth = 10, min_samples_leaf = 12))

RandomForestClassifier(max_depth=10, min_samples_leaf=12, n_estimators=8 Accuracy
Accuracy:  0.8376623376623377 
Classification Report: 
               precision    recall  f1-score   support

         0.0       1.00      0.48      0.65        48
         1.0       0.81      1.00      0.89       106

    accuracy                           0.84       154
   macro avg       0.90      0.74      0.77       154
weighted avg       0.87      0.84      0.82       154
 
Confusion Matrix: 
 [[ 23  25]
 [  0 106]]
Training Accuracy: 0.8
Testing Accuracy: 0.8376623376623377




Building a Predictive System


In [33]:
input_data = (1.0,1.0,0,0.0,1.0,3000,0.0,66.000000,6.0,1.0,2.0)

# changing input data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the numpy array
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = lr.predict(input_data_reshaped)
print(prediction)


if (prediction[0] == 0):
  print("The Person does not get a loan")

else:
  print("The Person gets a loan")

[1.]
The Person gets a loan


c:\Users\KIIT\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
